### ISSUE TITLE
Wrong error message displayed (for addlog)

### ISSUE THREAD

**Issue by zhiyi12345** [AY2425S1-CS2103T-W13-3/tp#112]
<img width="1101" alt="Screenshot 2024-10-23 at 1 44 25 PM" src="https://github.com/user-attachments/assets/c25c65ea-fad1-43b5-b14c-c974cefe2eb2">

Should not be showing incorrect error message.

S12345678Z does not exist yet, so should be no such person found and not incorrect format as format is correct

**Comment by t-leongchuan** [comment]
This likely goes under issue #106 instead
