### ISSUE TITLE
add command still uses l/date|entry

### ISSUE THREAD

**Issue by zhiyi12345** [AY2425S1-CS2103T-W13-3/tp#131]

**Comment by t-leongchuan** [comment]
This issue seems to already be fixed.

**Comment by zhiyi12345** [comment]
> This issue seems to already be fixed.

Correct me if im wrong, I believe it has only been fix for addlog command(referring to #121), but not for add command

**Comment by slidings** [comment]
can we remove it entirely?

**Comment by zhiyi12345** [comment]
> can we remove it entirely?
I think can is can, Im gna go ahead and remove it
