### ISSUE TITLE
Delete command asks you to confirm before checking validity of the patient

### ISSUE THREAD

**Issue by slidings** [AY2425S1-CS2103T-W13-3/tp#180]
Minor bug: When deleting invalid index, it prompts user to confirm delete before checking if its even valid
![image](https://github.com/user-attachments/assets/3af0059e-bc86-497a-a8ca-183748b0f5ae)

**Comment by jeanyang04** [comment]
This has been fixed in my pull request for the new cancel Command

**Comment by slidings** [comment]
Close by pr #178
