### ISSUE TITLE
No error message when adding invalid log entry

### ISSUE THREAD

**Issue by jeanyang04** [AY2425S1-CS2103T-W13-3/tp#200]
![image](https://github.com/user-attachments/assets/9e174ca9-5e86-4457-9a86-c162d8d9e840)
![image](https://github.com/user-attachments/assets/58ff0e47-4bb7-46f4-a2ba-4089e687713f)

When empty log entry is entered, there is no handling of the error, so the program just does nothing.

**Comment by zhiyi12345** [comment]
<img width="566" alt="Screenshot 2024-11-04 at 2 08 11 AM" src="https://github.com/user-attachments/assets/415272e4-07bd-4514-af11-a73667270356">
Error msg is only displaying on terminal
