### ISSUE TITLE
Add log will switch view back to list

### ISSUE THREAD

**Issue by jeanyang04** [AY2425S1-CS2103T-W13-3/tp#204]
When in `logs` view, adding a new log will switch the view back to `list` view

**Comment by t-leongchuan** [comment]
I implemented it in `MainWindow` so that there is logic to switch back to the Person List view when other commands apart from `logs` is used.

It is not perfect but it's a start.

**Comment by t-leongchuan** [comment]
Technically resolved as we removed toggling button and only allow switching to session log panel with `logs`. Any other command will revert back to the Person Contact list.

**Comment by zhiyi12345** [comment]
> Technically resolved as we removed toggling button and only allow switching to session log panel with `logs`. Any other command will revert back to the Person Contact list.

Im slightly confused, do you mean its on purpose that adding a log will jump back to person list and to see the log added, we have to key in log i/

**Comment by t-leongchuan** [comment]
Yup. Rationale is that the UI does not have a UI manager where the individual components have listeners to refresh and update GUI components.

This way, it is more stable as we can guarantee that the execution of commands will always lead to up-to-date ui components.
