### ISSUE TITLE
Add identical logs are allowed but does not show up

### ISSUE THREAD

**Issue by jeanyang04** [AY2425S1-CS2103T-W13-3/tp#205]
Not sure if this is a bug, but if identical logs are added, (same date, same content), it does get added, but it does not show up as duplicate log inside logs list.

**Comment by zhiyi12345** [comment]
yes this is a bug, but should we only allow one log/day. so its considered "identical" if same day as 1 patient will have at most 1 visit/day. So raise error if same date

**Comment by zhiyi12345** [comment]
similar to issue #128

**Comment by t-leongchuan** [comment]
The issue is that Logs is implemented as a Set<Log>. There is currently no logic in `AddLogCommand` to detect whether the log that the user plans to add is already present in Set<Log>.
