### ISSUE TITLE
Only one error message when there are multiple errors

### ISSUE THREAD

**Issue by junyi73** [AY2425S1-CS2103T-W13-3/tp#219]
![image](https://github.com/user-attachments/assets/3c509f87-cdb9-45b5-b01d-19a56b4bacf4)

Only one error message is show when there are multiple errors like the phone number is incorrect and the status is also incorrect.

**Comment by zhiyi12345** [comment]
Fixed via issue #157  and pr #226 
We will only throw the first error (AB3 implementation), so in this case the wrong phone number after the constraint is changed from 3 digit to sg context.
