### ISSUE TITLE
Logs list does not get updated immediately after add log command

### ISSUE THREAD

**Issue by slidings** [AY2425S1-CS2103T-W13-3/tp#223]
![image](https://github.com/user-attachments/assets/723e3964-2e62-4b95-a9e2-f1b2c9410060)

**Comment by t-leongchuan** [comment]
Technically resolved as now we do not allow toggling between panels.

**Comment by t-leongchuan** [comment]
Refer to #204 for this.

TLDR; we do not have a central UI manager where we can attach listeners to ensure every component (visible to the user) is up to date.

As of now, `logs` is the only one capable of pulling the latest copy of session log.
