### ISSUE TITLE
[PE-D][Tester C] Accepted values for phone numbers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-3/tp#295]
In Singapore, an individual may have a phone number that begins with the digit '6' (i.e. landline numbers).
Perhaps, you may accept the digit 6 as well or state in the UG that only handphone numbers are accepted.

![Screenshot 2024-11-08 at 4.27.47 PM.png](https://raw.githubusercontent.com/Ponharish/ped/main/files/cd11f4d3-e1e2-492b-943a-776e9be309f7.png)

The command used in this case
`add n/Alice i/S9384729F p/62601234 e/abc@xyz.com a/NUS s/Low`

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Ponharish/ped#2

**Comment by slidings** [comment]
can consider adding

**Comment by t-leongchuan** [comment]
Likely better to just write in UG that only handphone numbers are accepted.

Add under UG that we do not accept landline numbers and `1800-` numbers and other caveats.
