### ISSUE TITLE
[PE-D][Tester D] Unable To Add New User

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W13-3/tp#296]
# Description

Trying to add a new user results in an irrelevant (and wrong/misleading) error that NRIC must be 9 characters long.

# Steps To Replicate
**Note:** I'm not sure if these are the exact steps to replicate, but the problem started as I followed these sequence of steps (might be the case when trying to add one after another).
1. Add a person: ``add n/John Doe i/S1234567D p/98765432 e/johnd@example.com a/John street, block 123, #01-01 s/LOW``
2. Try adding another person (e.g. ``add n/Jacob Hempry i/S1234122D p/83212279 e/jacob@example.com a/Hempry street, block 5021, #01-01 s/HIGH``).

# Screenshot(s)

![image.png](https://raw.githubusercontent.com/ashea10/ped/main/files/3002293f-838f-41df-a903-53510a9e81c8.png)

# Reason For Severity
Adding a user is probably the most important command for a contact book.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: ashea10/ped#2

**Comment by t-leongchuan** [comment]
Likely due to difficulty in NRIC verification. Likely need to redirect users in the UG to a webpage for how our program checks for NRIC, and give some sample NRIC
