### ISSUE TITLE
[PE-D][Tester C] Potential misinterpretation of log tag

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-3/tp#310]
The existing tag to add logs is `/l` - a lowercase l which looks very similar to uppercase i - `/I`. This may potentially confuse new users.

![Screenshot 2024-11-08 at 4.54.29 PM.png](https://raw.githubusercontent.com/Ponharish/ped/main/files/118945ee-56e6-4aff-9416-65afc0db2641.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Ponharish/ped#5

**Comment by slidings** [comment]
maybe mention all flags are small letters in UG/DG
