### ISSUE TITLE
[PE-D][Tester A] Command to toggle bag to the list of contacts is not well documented in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W13-3/tp#340]
It was a bit confusing as a new user to try and exit the logs page as it was not mentioned anywhere in the UG. 

Suggestions:

- Give explicit instuctions on how to navigate back to the list of contacts.

Examples:

![image.png](https://raw.githubusercontent.com/Airiinnn/ped/main/files/2db5321d-1176-4e2e-854f-b9794e485e62.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Airiinnn/ped#12

**Comment by t-leongchuan** [comment]
Need to add a quick section on Switching between tabs
